### ISSUE TITLE
Alternative 'else' syntax

### ISSUE THREAD

**Issue by coladict** [samshadwell/TrumpScript#13]
I think it should be 'or else', to sound more like a threat.

**Comment by codingjoe** [comment]
:+1:

**Comment by erip** [comment]
:+1:

**Comment by themightywrighty** [comment]
:smiley:

**Comment by evanv** [comment]
:+1:

**Comment by EdgeCaseBerg** [comment]
brilliant :+1:

**Comment by iamserena** [comment]
so much yes

**Comment by phroggyy** [comment]
How is `else if` treated in this context? Same way as now?

**Comment by coladict** [comment]
Maybe it would have an optional comma `or else, if`.

**Comment by philipengberg** [comment]
:+1:

**Comment by hardlianotion** [comment]
I think the opening if statement should be silent and implied:

Pay(10000000):
    Hurt(nobody)
Or else:
    Suffer(consequences)

Works nicely

**Comment by phroggyy** [comment]
@hardlianotion so basically some look ahead to check if the next line
contains "Or else"?
ma 25. tammikuuta 2016 klo 1.31 hardlianotion <notifications@github.com>
kirjoitti:

**Comment by CryoBrown** [comment]
No. That would require unbounded look ahead and I'm not writing it.

**Comment by CryoBrown** [comment]
Also where does the IF statement implicitly go in there? before pay, before hurt, or right before the or else? do Pay and Hurt have returns?
