### ISSUE TITLE
Support for `build -Wall` compiler options

### ISSUE THREAD

**Issue by atedja** [samshadwell/TrumpScript#136]
If [GCC](https://gcc.gnu.org/onlinedocs/gcc/Standard-Libraries.html#index-Wall-4470) has `-Wall` option, TrumpScript should also have the `-Wall` because it's that great of a programming language.

**Comment by samshadwell** [comment]
Actually, it might be cool if we use that to enable the feature where we disable Mexican locales.

**Comment by g3wanghc** [comment]
@samshadwell  Its already the default behaviour.

```
if MX' in loc:
    raise Utils.SystemException("I will build a great [fire]wall on our southern border.")
```

**Comment by samshadwell** [comment]
Yeah, @g3wanghc, I was saying we could disable it by default, and only enable it when the -Wall flag is set

**Comment by g3wanghc** [comment]
That sounds pretty fun. 👍

**Comment by samshadwell** [comment]
Added by c6b7e424a3f86206e7cb9a4f169e03ceb8101eab
