### ISSUE TITLE
Make "Rosie O'donnell" a null reference 

### ISSUE THREAD

**Issue by killVung** [samshadwell/TrumpScript#148]
We hate her, no doubt, so does Trump, so whenever there is a reference of her name "Rosie O'donnell", it will become point to null as "Jeb", or, in Python perspective, None.

Or even worse, point directly to null pointer in C that cause Segmentation fault, because "Rosie O'donnell" just had so much impact.

**Comment by fredkneeland-wf** [comment]
Add the hacktoberfest label and I will do this, and any of the other issues you have listed... :)

**Comment by killVung** [comment]
@samshadwell 
@CryoBrown

**Comment by samshadwell** [comment]
The language right now doesn't really have any concept of objects, but if you want to make this throw an exception, be my guest.
