### ISSUE TITLE
Where's China?

### ISSUE THREAD

**Issue by sshine** [samshadwell/TrumpScript#15]
Donald Trump loves China so much one should think of a language primitive with this name.

https://www.youtube.com/watch?v=RDrfE9I8_hs

Possibly as a generic I/O device?

**Comment by CryoBrown** [comment]
The first thing he says in that video is a valid Trumpscript statement, so I'm pretty happy with the language now.

Let's say "China"

**Comment by iamserena** [comment]
China all the time
