### ISSUE TITLE
Ending Programs with 'America is Great' vs. 'Make America Great Again'

### ISSUE THREAD

**Issue by liamnickell** [samshadwell/TrumpScript#150]
I think that it may be more in line with our favorite small-fingered vulgarian's beliefs if TrumpScript files end with 'Make America Great Again' instead of 'America is Great.' This is due to the fact that the Donald has had a major tendency to not praise but instead lambaste the current state of America. He wants to 'Make America Great **Again**,' so perhaps it would be better suited for Drumpf's personal programming language to require the user to embrace his ideals as opposed to admitting that America is already great? Just a thought.

**Comment by samshadwell** [comment]
This programming language was written under the (correct) assumption that Donald would in fact become the POTUS. We don't want to have to change the language after it is already in production, and so I think assuming Trump has won the presidency and brought greatness back to America is a fair assumption.

**Comment by liamnickell** [comment]
Ah, I see. Well, you are indeed correct about that assumption (as long as every polling station in the swing states isn't rigged by 'Crooked Hilary' and there are enough [Official 'Trump Election Observers'](https://www.donaldjtrump.com/lp/volunteer-to-be-a-trump-election-observer) to keep a watchful eye over the polling stations on election day).

**Comment by samshadwell** [comment]
You're right, when we designed the language we had no idea how crooked the criminal Clinton truly is. We can only hope that the supporters of the one true candidate are strong enough to resist her corrupt ways.

**Comment by samshadwell** [comment]
See a76f078
