### ISSUE TITLE
Please standardize all program file extension to ".tr"

### ISSUE THREAD

**Issue by killVung** [samshadwell/TrumpScript#153]
I keep seeing "*.txt" and "*.tr" and have no idea what to do with it...

Perhaps we can implement a new features on dealing with this extension

**Comment by killVung** [comment]
@samshadwell 
@CryoBrown

**Comment by samshadwell** [comment]
You can submit a PR to convert them all to .tr if you want. I don't want to change the interpreter to only accept .tr files, though. Just like GCC will accept any file regardless of extension, I think our interpreter should do the same.
