### ISSUE TITLE
icmp socket : permission denied

### ISSUE THREAD

**Issue by stealthrabbi** [samshadwell/TrumpScript#155]
Every file I run reports this error twice, and then I get expected output.

> mark@MYPC:~/TrumpScript/test/test_files$ TRUMP huge_test.tr
> ping: icmp open socket: Permission denied
> ping: icmp open socket: Permission denied
> huge

**Comment by stealthrabbi** [comment]
Note, I was running on Ubuntu for Windows 10.

**Comment by samshadwell** [comment]
Can you comment out line 35 in utils.py?

I'm guessing this is some issue with the SSL stuff.

**Comment by samshadwell** [comment]
Actually, it's probably the call to no_commie_network() on line 36. Try commenting that out instead.

**Comment by stealthrabbi** [comment]
yeah, it was line 36.

**Comment by samshadwell** [comment]
See a76f078
