### ISSUE TITLE
New feature: "Wrong"

### ISSUE THREAD

**Issue by Grant-Nelson** [samshadwell/TrumpScript#161]
`Wrong` is like throwing exception except, like a segfault, there is no additional information.
It isn't handled by a try-catch. Depending on how `Wrong` is implemented it could halt the program or it could simply be printed to the console without actually doing anything other than indicating disapproval of the running code. Possibly `Wrong` only prints and `Wrong!` halts. Taking Trump's lead, I haven't really thought through this idea but it sounds good right now.

**Comment by killVung** [comment]
and you may also use `Regret` to unraise the exception as well
[](https://youtu.be/ipBvoEDBOpw)

**Comment by samshadwell** [comment]
See a76f078
