### ISSUE TITLE
Add President

### ISSUE THREAD

**Issue by killvung** [samshadwell/TrumpScript#165]
I don't know
Think of what you can do with this feature, he is going to win anyway!~!

**Comment by g3wanghc** [comment]
well boys, it was a pleasure working on this project with all of ya

**Comment by JesseTG** [comment]
I am embarrassed to be an American.  :(

**Comment by danielwegener** [comment]
Time to release a 1.0?

**Comment by painhardcore** [comment]
His won

**Comment by bryanlimy** [comment]
release 1.0?

**Comment by samshadwell** [comment]
See a76f078
