### ISSUE TITLE
Every line should include at least one 'china'

### ISSUE THREAD

**Issue by graysongs** [samshadwell/TrumpScript#167]
Because too much 'china'

**Comment by tourbillon1994** [comment]
as a chinese , I really support this suggestion. :+1:

**Comment by wizzwizz4** [comment]
-1 Not enough America. China is far inferior to the greatness of America, for America is before any other country.

**Comment by NKUCodingCat** [comment]
+1 as a Chinese

**Comment by yaochao** [comment]
我在静静的看着你们😆

**Comment by lingsamuel** [comment]
America is not enough.

**Comment by boliza** [comment]
+1 as a Chinese

**Comment by samshadwell** [comment]
See a76f078
