### ISSUE TITLE
Request for adding the former president of PR China, JiangZemin, to vocabulary

### ISSUE THREAD

**Issue by NKUCodingCat** [samshadwell/TrumpScript#169]
He is who he is, and some of people in china, claimed as mogician(a hybridize of magician and MO in Chinese), compared Donald J. Trump to him and summarize three important speech, as Jiang did, of Trump(included the Gettysburg one, of course). So I hereby request that add following words to vocabulary list:

1. Jiang
2. JiangZemin
3. Zemin
4. JiangZhuXi (which means President Jiang in chinese, famous when Jiang Rage a reporter from HK)
5. JiangPlus1s
6. Plus1s
6. TheElder
7. Wallace(for Mike Wallace, who had the interview)

+1s (this is the signal and --EOF-- for Mogicians, means donate a 1-second long life to ex-President Jiang, somewhat like _LongLive the CHAIRMAN MAO_ but we just donate 1 second, great deal)

**Comment by jiangshanmeta** [comment]
+1s 

Don`t make big news.

**Comment by Perterually** [comment]
+1s

**Comment by jinguodian** [comment]
+1s,  he also love The Gettysburg Address

**Comment by sdjksdafji** [comment]
+1s

**Comment by pacumlaft** [comment]
+1s ,nothing to speak!

**Comment by HaloWang** [comment]
+1s

**Comment by thelastlin** [comment]
+1s

**Comment by tioover** [comment]
add(time.second(1.0))

**Comment by huntzhan** [comment]
+1s

**Comment by kdwycz** [comment]
+1s

**Comment by ChanJLee** [comment]
+1s

**Comment by wzy9607** [comment]
+1s

**Comment by hangim** [comment]
One more second

**Comment by clippit** [comment]
+1s

**Comment by hczhcz** [comment]
+1s

**Comment by KIDJourney** [comment]
+1s

**Comment by wplct** [comment]
+1s

**Comment by wyj5230** [comment]
My mogic will tear u apart.

**Comment by SinTi** [comment]
+1s

**Comment by cxgreat2014** [comment]
+1s

**Comment by qratosone** [comment]
+1s

**Comment by disoul** [comment]
+1s

**Comment by ruiann** [comment]
+1s

**Comment by graysongs** [comment]
+1s

**Comment by USOMOE** [comment]
+1s

**Comment by SuneBear** [comment]
Never too young, too simple but sometimes moha. https://github.com/Mohaer/MoHa

**Comment by GuiJu** [comment]
I'm angry！

**Comment by x1ah** [comment]
+1s

**Comment by ex44559** [comment]
+1s

**Comment by Felamande** [comment]
Western which countries I haven't been to, America's Wallace don't know how tall than you, I am with him talking and laughing.

**Comment by yaochao** [comment]
+1s

**Comment by Muruwu** [comment]
we talk cheerfully and humourously

**Comment by Chrisplus** [comment]
Do NOT always think of making a big news.

**Comment by 0312birdzhang** [comment]
+1s

**Comment by QShen3** [comment]
+1s

**Comment by MrEasonYang** [comment]
+1s

**Comment by NosearY** [comment]
+1s

**Comment by evilcoda** [comment]
Excited though, don't tryna make a big news all day !

**Comment by ninjadq** [comment]
Do you know how much Wallace who comes from USA is higher than you guys above?

**Comment by Danielhu229** [comment]
+1s

**Comment by lrh3321** [comment]
+1 I'm angry!💢

**Comment by ciknight** [comment]
++1

**Comment by 4ever911** [comment]
navie

**Comment by doomsplayer** [comment]
+1s

**Comment by dnc1994** [comment]
+1s

**Comment by EmolLi** [comment]
++1

**Comment by samshadwell** [comment]
I'll be honest, I don't really have the background in Chinese politics to understand this joke.

**Comment by CryoBrown** [comment]
Yeah I'm pretty confused as well

**Comment by hczhcz** [comment]
@samshadwell @CryoBrown The joke comes from [here](https://www.youtube.com/watch?v=5GIj2BVJS2A)

**Comment by hczhcz** [comment]
And Chinese netizens believe that.. by saying "+1s", Jiang's life would be extended by one second

**Comment by ericjee** [comment]
+1s, I have no comment!

**Comment by ymback** [comment]
I have to say, +1s
You young guys, don't make a big news!

**Comment by tourbillon1994** [comment]
Don't make a big news !
From the ancient one

**Comment by sunsan05** [comment]
+1s

**Comment by NKUCodingCat** [comment]
@samshadwell @CryoBrown  FYI, you can take a look right [here](http://cn.nytimes.com/china/20151021/c21sino-jiang/en-us/), a blog by NYT

**Comment by mdw771** [comment]
+1s.
A metaclass should be made specifically for HIM with `__add__` overloaded with `self.life += time.time(1)`.

**Comment by DongSky** [comment]
+1s

**Comment by xchuwenbo** [comment]
you too young too simple. sometimes naive

**Comment by TennyZhuang** [comment]
+1s

**Comment by ZoharWang** [comment]
+1s

**Comment by losfair** [comment]
+1s

**Comment by KelaKim** [comment]
+1s 🐸 Basic law is great

**Comment by liwanglin12** [comment]
+1s 🐸

**Comment by wbsdty331** [comment]
+1s
Everything should do with the basic law

**Comment by G-monitor** [comment]
+1s

**Comment by qq915458022** [comment]
+1s

**Comment by MittWillson** [comment]
+1s

**Comment by wjm2038** [comment]
+1s

**Comment by SnowOnion** [comment]
@NKUCodingCat Maybe it's better to add the urls of the video and NYT blog to the content of this issue.

p.s. Why is there a --EOF-- ? Do you mean that "+1s" sometimes act as EOF, Q.E.D. and “幸甚至哉，歌以咏志”？

**Comment by TroyXun** [comment]
+1s

**Comment by NKUCodingCat** [comment]
@SnowOnion You get it

**Comment by wbsdty331** [comment]
@SnowOnion I think “无可奉告” is better than “幸甚至哉，歌以咏志”

**Comment by charlestian** [comment]
Don't always try to make big news.

**Comment by wbsdty331** [comment]
Recently, the European Union has published a report, in which it said Beijing will interfere into Hong Kong's rule of law. What's your opinion?

**Comment by SnowOnion** [comment]
@wbsdty331 Great, EOF have similar meaning to “无可奉告”。

And, wow, I hesitated when choosing from "." and "。" when trying to end a sentence containing both 中文 and Egnlish...

**Comment by samshadwell** [comment]
See a76f078
