### ISSUE TITLE
Recent builds seem to have broken democracy

### ISSUE THREAD

**Issue by criswell** [samshadwell/TrumpScript#179]
So, I've been running all our code on TrumpScript for the past couple of months, and I just noticed yesterday that all my builds are failing. Other people seem to be having the same issue, at least, that's what everyone is saying, so it must be true. Help?

* Staging environment: Rampant misogyny and xenophobia
* Expected result: Make America Great Again
* Actual Result: Nodes with protest exceptions, and all builds red.

**Comment by ssaavedra** [comment]
Red builds should be ok, though. Green is not a color in the American flag, it's more like Mexican. Maybe it's an implementation problem in the Wall.

**Comment by samshadwell** [comment]
See a76f078
