### ISSUE TITLE
Use the keyword "grab" to assign values

### ISSUE THREAD

**Issue by weirandeng** [samshadwell/TrumpScript#183]
Can we get rid of the equal sign "=" and use the keyword "grab" to assign values?

Make programming great again!

**Comment by NKUCodingCat** [comment]
and the right value should be pack in Pu**y while using grab

Just like `Trump grab pussy, 5;` (it is not a grammar sugar but a tremendous grammar disaster)

**Comment by CryoBrown** [comment]
This language doesn't even use the = operator

**Comment by samshadwell** [comment]
See a76f078
