### ISSUE TITLE
Support `tremendous int` as syntactic sugar of `long long int`

### ISSUE THREAD

**Issue by AldoMX** [samshadwell/TrumpScript#185]

**Comment by pcchou** [comment]
Why isn't it `int bigly`?

**Comment by CryoBrown** [comment]
This language isn't even typed

**Comment by AldoMX** [comment]
Why not? Trump is known for preferring some types over others; OTOH I would suggest to implement a Foreign Function Interface as a workaround, but that also goes against Trump's view of a perfect language.

**Comment by samshadwell** [comment]
See a76f078
