### ISSUE TITLE
replace "fact" and "lie" with more accurate words

### ISSUE THREAD

**Issue by mar77i** [samshadwell/TrumpScript#186]
Things that are sold as "facts" and "lies" have become somewhat arbitrary in 2016, so I think it's not a good idea to base one's program execution on facts only.
Let's use 'opinion' and 'fact' instead, and give 'opinion' the ultimate say.

**Comment by pllim** [comment]
Superseded by #201

**Comment by samshadwell** [comment]
See a76f078
