### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by marco-a** [samshadwell/TrumpScript#190]
I want to use this for my next product, is this production ready?

**Comment by samshadwell** [comment]
Oh, absolutely not.

**Comment by StevenGann** [comment]
Of course TrumpScript is ready. It makes great products, the best products, you'll love it. Don't worry about what @samshadwell says. I know about TrumpScript. I know more about Trumpscript than even the owner. Believe me.

**Comment by samshadwell** [comment]
See a76f078
