### ISSUE TITLE
Add `alternative fact` keyword

### ISSUE THREAD

**Issue by nloveladyallen** [samshadwell/TrumpScript#201]
Regarding the `lie` keyword: don't be so overly dramatic about it. You're saying it's a `lie`, and they're giving—our press secretary, Sean Spicer, gave `alternative fact`s to that.

**Comment by tjvr** [comment]
from [this tweet](https://twitter.com/Mythic_Beasts/status/823574588672053252):
```
Python 2.7.10
>>> #President's favourite programming language
... 
>>> True=False
>>> print True
False
1 reply 5 retweets 6 likes
```

**Comment by samshadwell** [comment]
See a76f0783cebc87297be9282398e94e734373171e
