### ISSUE TITLE
division gives float

### ISSUE THREAD

**Issue by heitorPB** [samshadwell/TrumpScript#21]
the following code:

```javascript
make great 1000001
make world 1000000

i want to make America, great over world;
say america

America is great.
```

produces this output:

    Compiled, starting execution
    -------------------
    
    1.000001

but, it should be 1, right?
I mean, one milion?

**Comment by CryoBrown** [comment]
Well, we already knew this happened, but we aren't sure that we shouldn't allow people to construct floats from integer literals this way. It feels kinda like some tax dodges or cooking the books, and also allows for people to write more complicated things, and more importantly, things that look more complicated.

**Comment by samshadwell** [comment]
The plan was to have division round up, so this is pending.

**Comment by jameswhite** [comment]
I feel "division" should be renamed "goesinta" as in `three goesinta twelve four times`

**Comment by samshadwell** [comment]
Ooh, I do like that.

**Comment by CryoBrown** [comment]
Yeah it's also pretty easy as far as altering the tokenizer. We could look at changing the way we check for equality with keywords to be an underlying defaultdict to clean up that code, especially if we expect to add more keywords or aliases for existing keywords.

**Comment by asciifaceman** [comment]
I say allow floats but find a creative way to deal with them.

* Stash the decimal in an overseas namespaced account and call it a rounding error?
* Put the decimal in a cumulative savings account to gift to your child process
* etc

**Comment by samshadwell** [comment]
#58
