### ISSUE TITLE
Language distinguishes between True and False

### ISSUE THREAD

**Issue by isaacfreeman** [samshadwell/TrumpScript#26]
This seems to be a mistake:
> Instead of `True` and `False`, we have `fact` and `lie`.

Distinguishing `True` from `False` or `fact` from `lie` runs entirely counter to established practice for Trump. TrumpScript should therefore eschew the reality-based concepts of `True` and `False`. All boolean operations should simply evaluate to `fact`.

**Comment by samshadwell** [comment]
This is what the liberal media wants you to believe. I know that Hillary Clinton "lies like crazy about everything," and that despite the best efforts of the liberal media, the illustrious Trump would never do that to us.

**Comment by asciifaceman** [comment]
I think I see what OP means here.

We should only define `FACT`S, everything else is intrinsically a `lie`
