### ISSUE TITLE
ImportError: No module named src.trumpscript.compiler

### ISSUE THREAD

**Issue by hpincket** [samshadwell/TrumpScript#28]
Maybe this should be obvious, but any help would be appreciated.

````
Traceback (most recent call last):
  File "src/trumpscript/main.py", line 3, in <module>
    import src.trumpscript.compiler
ImportError: No module named src.trumpscript.compiler
````

**Comment by samshadwell** [comment]
Did you add the directory you checked out to you Python path?

**Comment by hpincket** [comment]
I added it to my bash path (using export PATH=$PATH:/etc). I didn't do anything with the python path.

**Comment by samshadwell** [comment]
https://github.com/samshadwell/TrumpScript/tree/26508eff5c7a40e36d601a2e1633ebf0157e4e3b

Can you try checking out and running that version?

**Comment by maaarghk** [comment]
@hpincket - you should also run 
```
export PYTHONPATH=$PYTHONPATH:`pwd`
```
from the directory you checked out.

**Comment by benwaffle** [comment]
`$ python3 -m src.trumpscript.main`

**Comment by hpincket** [comment]
Thanks for the help everyone! I didn't try everything, but @benwaffle, your idea worked just fine.

For reference I changed TRUMP to 
````
python3 -m src.trumpscript.main $1
````
