### ISSUE TITLE
TrumpScript should ship with Woman object with appropriate methods pre-defined

### ISSUE THREAD

**Issue by evanv** [samshadwell/TrumpScript#29]
TrumpScript should ship out of the box with a pre-defined Woman object with methods for Cooking, Cleaning, Bleeding out of Everywhere, and Wearing Bikinis in Trump-Sponsored Beauty Pageants

**Comment by iamserena** [comment]
+1

**Comment by christopherL91** [comment]
+1

**Comment by mung3r** [comment]
Woman object should also be subclassed/extended as Daughter object with added method datingFather()
