### ISSUE TITLE
TrumpScript should arbitrarily demand to see SSL certificates from any machine that interacts with it

### ISSUE THREAD

**Issue by evanv** [samshadwell/TrumpScript#30]
Cause TrumpScript doesn't think you really have a valid SSL Certificate

**Comment by deadlyicon** [comment]
+1

**Comment by iamserena** [comment]
+1 
(I am dying of laughter right now. This is too much for me.)

**Comment by numinit** [comment]
What about a version of this that also warns if any Chinese CA certs exist on your system?

**Comment by numinit** [comment]
#38
