### ISSUE TITLE
can I deport a module?

### ISSUE THREAD

**Issue by matchdav** [samshadwell/TrumpScript#36]
I feel like if I'm unhappy with the results of

```
from Syria import refugees
```
I should be able to at a later point in the program specify that this module be removed from memory.

```
from America deport refugees
```

**Comment by numinit** [comment]
excellent idea

**Comment by jcgertig** [comment]
I think the proper syntax would be 

```
import refugees from Syria
```
and

```
deport  refugees from America
``` 

just so we are following TS6

**Comment by matchdav** [comment]
I did notice that TrumpScript does not allow import statements.  

However, that shouldn't mean you can't be deported if you are already there.

e.g. 

```
deport mexicans from America
# mexicans should no longer be defined in this context
if mexicans?
    complain "They are taking our jobs."
else
   say "America is great again."
America is great
```

**Comment by alpheidae** [comment]
Perhaps all imports should be banned until the program has "figured out what's going on."
America is great.

**Comment by asciifaceman** [comment]
we should be able to export objects as well, but only with a 25% tariff

**Comment by tcyrus** [comment]
:+1:
