### ISSUE TITLE
License? MIT license? seriously?

### ISSUE THREAD

**Issue by pombredanne** [samshadwell/TrumpScript#39]
I think there is a serious issue with the license of this project.
`MIT` license? a German word? And furthermore a license that is both considered as permissive or liberal. This is really not fitting. I suggest to draft a new license which should be some fiercely proprietary license. With a fee attached in the Trumpscript integer range.
America is great.

**Comment by gnerkus** [comment]
:+1:

**Comment by samshadwell** [comment]
You're right, a capitalist economy is built on the concept of intellectual property. I can't believe I've been so liberal with my thoughts. That communist propaganda has been getting to me.

**Comment by tachyons** [comment]
:+1:
