### ISSUE TITLE
TrumpScript should not compute in China or Mexico

### ISSUE THREAD

**Issue by adamierymenko** [samshadwell/TrumpScript#41]
It should use GeoIP from its current host to refuse to run in China or Mexico, and should also throw an exception if any Unicode characters belonging to Spanish or Arabic are detected.

**Comment by numinit** [comment]
>It should use GeoIP from its current host to refuse to run in China or Mexico

Looks like #27 is what you're talking about

>should also throw an exception if any Unicode characters belonging to Spanish or Arabic are detected

The variable names you can use are whitelisted anyway, so I think this happens by default

**Comment by someara** [comment]
It should at least throw a warning: "There will be hell toupee."

**Comment by samshadwell** [comment]
Just added Mexico to the set of banned locales.
