### ISSUE TITLE
TrumpScript programs should always require elevated privileges to run...

### ISSUE THREAD

**Issue by alpheidae** [samshadwell/TrumpScript#42]
...because America should always deal from a position of strength or get crushed every time.
~~Glory to Arstotzka~~ America is great.

**Comment by numinit** [comment]
#43

**Comment by samshadwell** [comment]
America doesn't need to run as root to be in a position of strength

**Comment by numinit** [comment]
Amended #43

**Comment by samshadwell** [comment]
You're forgiven, fellow American.
