### ISSUE TITLE
On building walls

### ISSUE THREAD

**Issue by asciifaceman** [samshadwell/TrumpScript#44]
I want to write WOP (Wall-oriented programs) in TrumpScript, is there any chance of Walls being implemented? Specifically, ones paid for by Mexico. 

some other interesting features to consider:

[ ] negotiating for system resources or system objects, to `get the best guys`
[ ] `Believe Me` for premature or flagged exits (`Believe Me 1`, `Believe Me 0`, etc)
[ ] Sometimes the best variables are the ones you don't define at all
[ ] You have to code anyways, why not code big? We should implement a minimum amount of code to make a program functional (setup, teardown?)
[ ] Any feminine variable should be flirted with
[ ] There should be an element of Luck when running TrumpScript
[ ] Exports should be allowed, but be taxed 25%
[ ] Currency math should be handled by a yam-aka-namespaced handler 
[ ] Scripts should [fail to run] be destroyed/fired if it detects any form of "Rosie O'Donnell" within itself
[x] Error should not be captured, I like errors that aren't captured

**Comment by AnneTheAgile** [comment]
This ticket should be reopened. I see the allowed words includes 'object'. In fact, all items in TrumpScript are required to live in an isolated, walled off context. Thus, to ensure proper building of  walled gardens of ideas, countries, and apartment buildings for the rich, we need to override 'object' to inherit from 'wall', as suggested above.
Anne
Reference;    https://github.com/samshadwell/TrumpScript/search?utf8=%E2%9C%93&q=object
