### ISSUE TITLE
I is Donald Trump?

### ISSUE THREAD

**Issue by S-YOU** [samshadwell/TrumpScript#46]
This line

> I is Donald Trump it time to tell you a fact

should be

> I am Donald Trump its time to tell you a fact

https://github.com/samshadwell/TrumpScript/blob/master/test/test_files/trump_vs_army.txt

**Comment by phroggyy** [comment]
The language currently does not support the `am` token.

**Comment by bsimser** [comment]
I feel an "am" PR coming on.

**Comment by samshadwell** [comment]
See a76f078
