### ISSUE TITLE
Any chance/plans for lists?

### ISSUE THREAD

**Issue by Zeldebeest** [samshadwell/TrumpScript#47]
I'd like to try and do http://stanford.edu/~jgrimmer/pol150b/Challenge1/challenge1.pdf in Trumpscript ...

**Comment by phroggyy** [comment]
We can call the type `Agenda`, that might cut it, political words and all. Hopefully, that can be a start for a good grammar, something along the lines of:

```
make Trump Agenda:
    1. "Win Election"
    2. "Profit"
```

Thoughts?

**Comment by tundey** [comment]
Lists are not allowed. Especially those by the govt.

**Comment by phroggyy** [comment]
Sure @tundey, hence the agenda naming. This will allow us to `sabotage
China's Agendas` in a future version.
America is great.
pe 22. tammikuuta 2016 klo 1.27 tundey <notifications@github.com> kirjoitti:

**Comment by tcyrus** [comment]
:+1:

**Comment by CryoBrown** [comment]
More complicated variables are on the list, right after things like functions and "actually working"

**Comment by samshadwell** [comment]
See a76f078
