### ISSUE TITLE
New keyword needed: Yuge!

### ISSUE THREAD

**Issue by tundey** [samshadwell/TrumpScript#49]
Please implement a new keyword "Yuge". It should do nothing and mean nothing. That way it can be sprinkled liberally in the code without affecting output. Or it could be a 3rd boolean option: fact, lie or yuge.

**Comment by phroggyy** [comment]
IIRC, any words that are not part of the language are ignored. You are free to use `yuge` to your liking.

**Comment by CryoBrown** [comment]
phroggyy, you would actually have to add yuge to the allowed_words list for that to work, otherwise the compiler will complain at you for not speaking english. 

Related: Sam did allow words matching a regular expression of the word "huge" with one or more u's to the allowed words check.
