### ISSUE TITLE
Why does this exist?

### ISSUE THREAD

**Issue by Toltar** [samshadwell/TrumpScript#52]
Why does this exist in the first place? Python is already great......

**Comment by nhtranngoc** [comment]
But we need to make Python great again.

**Comment by FalkoJoseph** [comment]
lmao

**Comment by bossjones** [comment]
lmaoooo so fucking creative lololol I can't hate on this at all.

**Comment by Toltar** [comment]
Python with America!

**Comment by RandomActPG** [comment]
Python was great once, before those other programming languages took over

**Comment by Deamon12** [comment]
Python just wasn't winning anymore.
