### ISSUE TITLE
Bombing

### ISSUE THREAD

**Issue by HuangYuSan** [samshadwell/TrumpScript#60]
We've got a problem with some terror group? Just bomb it away! I therefore suggest the use of the keyword `bomb` which catches all errors without further action. Got a faulty line in your code that throws errors all the time? Just bomb it away! Like this:

``` javascript
try {
  throw new Error();
} bomb
```

**Comment by HuangYuSan** [comment]
*all the time

**Comment by HuangYuSan** [comment]
I.e., `bomb` equals `catch (Error) {  }`

**Comment by dotlouis** [comment]
Ok I exploded... :bomb: in laughter. I love the idea !!!

**Comment by arnesahlberg** [comment]
I think the correct syntax would be demand/bomb instead of try/catch

    demand {
        statement;
    } bomb (error) {
        another statement;
    }

**Comment by HuangYuSan** [comment]
Well this would just be renaming `try` and `catch `, that's kinda boring to be honest

**Comment by samshadwell** [comment]
See a76f078
