### ISSUE TITLE
Making Python great again?

### ISSUE THREAD

**Issue by cyouden** [samshadwell/TrumpScript#64]
Python was originally developed in the Netherlands, why not use an American language, like C++? We need to return programming language design jobs to the USA!

**Comment by theroyalstudent** [comment]
+1

**Comment by jonathanGB** [comment]
But C++ was designed by Bjarne Stroustrup, a Danish...
As stated, "America never does anything halfway". We must choose a true American language.

**Comment by numinit** [comment]
To be truly American, TrumpScript should be self-hosting

**Comment by Jonathan50** [comment]
Design a subset of TrumpScript and write a compiler in machine code. Then implement TrumpScript in the subset of TrumpScript and compile it in the first compiler.

**Comment by maartenh** [comment]
To be sure no imports are involved, you'll need to ensure that all developers are native Americans.

**Comment by EmolLi** [comment]
no import allowed +1

**Comment by kirillDanshin** [comment]
why not use Golang? it developed by Google, and AFAIK Google is an American company.

**Comment by samshadwell** [comment]
See a76f078
