### ISSUE TITLE
TrumpScript should require a "small loan" of 1 million KB to execute

### ISSUE THREAD

**Issue by ProjectRevoTPP** [samshadwell/TrumpScript#67]
Just a small loan.

**Comment by ProjectRevoTPP** [comment]
This would make a "Hello, America" script 1GB, for the record.

**Comment by pkallos** [comment]
would make more sense to use 1 million bytes, instead of 1 million thousand bytes, no?

**Comment by ProjectRevoTPP** [comment]
Yeah, I guess.

**Comment by CryoBrown** [comment]
So require a MB of memory to start?

**Comment by ProjectRevoTPP** [comment]
Yeah, it's only a small loan of 1 million bytes after all.

**Comment by nolsen42** [comment]
But will it come with interest?

**Comment by GusCaplan** [comment]
```py
loan = bytearray(1000000)
if self.filedForBankrupcy: # always true :(
    loan.neverPayOff()
```

**Comment by killVung** [comment]
Just like how GusCaplan pointed out 
1 million KB wouldn't be a good reference, I prefer 1 million Byte
if len(file) <= byte(1000000):
    raise Exception("This program isn't rich enough to be recognised by our glorious TRUMP")

**Comment by samshadwell** [comment]
See a76f078
