### ISSUE TITLE
TrumpScript could allow imported code but impose tariffs by making it run slower

### ISSUE THREAD

**Issue by chrismaeda** [samshadwell/TrumpScript#68]
In order to allow imported code but put locally produced code on a level playing field, imported foreign code should be made to automatically run slower.   One way to do this would be to impose a delay when the foreign module is first imported.  A second way would be to have the VM automatically run imported code slower.  I don't know or care what the implementation costs are or what unintended consequences this will create.

**Comment by gilgm12** [comment]
+1

**Comment by CryoBrown** [comment]
Originally we wanted to pop up a link to a bitcoin wallet or paypal purchase button when importing.

**Comment by muschottkey** [comment]
+1

**Comment by ClaytonSmith** [comment]
+1

**Comment by GusCaplan** [comment]
guys there is a +1 button on comments you don't need to flood this place with +1

**Comment by samshadwell** [comment]
See a76f078
