### ISSUE TITLE
Type Inference Engine: Make everything classy by default

### ISSUE THREAD

**Issue by circlecycle** [samshadwell/TrumpScript#69]

**Comment by circlecycle** [comment]
Currently we support methods on strings like 

```
"   asdfasd   ".strip()
```

but we don't support 

```
1.real()
```

Can we modify the project to make everything as classy as possible by default? mmm... thanks.

**Comment by samshadwell** [comment]
Could you go into more detail on this one? Sorry, I don't typically do anything more than very small projects in Python, so I'm not used to all the conventions.

**Comment by samshadwell** [comment]
Also, we've been talking about maybe switching this whole project over to a statically typed language in the near future.

**Comment by ebrian** [comment]
@samshadwell I've written a toy language before (https://github.com/ebrian/axis). I'm in if you want the help, I love this project.

**Comment by CryoBrown** [comment]
Yeah because not having types blows hard

**Comment by dieseltravis** [comment]
Nice.

**Comment by samshadwell** [comment]
See a76f078
