### ISSUE TITLE
Should The Return Function Be "My Father Gave Me A Small Loan Of A Million [OBJECT]"

### ISSUE THREAD

**Issue by Ash-Bash** [samshadwell/TrumpScript#71]

**Comment by MemoLabra** [comment]
definitely +1

**Comment by C0D3FR3AK** [comment]
That would be a great addition to this language.

**Comment by CryoBrown** [comment]
Think smaller, that really bulks up the language for something we might expect to use more frequently if and when we put functions in

**Comment by Ash-Bash** [comment]
It Could Be "Small Loan Of A Million [OBJECT]"

**Comment by samshadwell** [comment]
See a76f078
