### ISSUE TITLE
Ban Arabic Numerials

### ISSUE THREAD

**Issue by jwhitehorn** [samshadwell/TrumpScript#76]
It's a well known fact that terrorists use numbers like 0,1,2,3,4,5,6,7,8, and 9.

The use of Arabic Numerials should be banned until this language's contributors have had a chance to look into what the freak is going on.

In the interim only Roman Numerials should be allowed.

**Comment by arnesahlberg** [comment]
Not Roman numerals!? All numbers should be written with proper american words.
    1000000000 + 34566724
could be written as
    onebillion plus thirtyfourmillionfivehundredsixtysixthousandsevenhundredtwentyfour

**Comment by udgw** [comment]
unmuslimize('1234567890')
then you can use these num chars.

**Comment by JustinCSafa** [comment]
@udgw Instead of "unmuslimize" we should name the function "convert".

**Comment by samshadwell** [comment]
See a76f078
