### ISSUE TITLE
Is this language going to be a serious programming language or just for play?

### ISSUE THREAD

**Issue by C0D3FR3AK** [samshadwell/TrumpScript#88]

**Comment by C0D3FR3AK** [comment]
If this is going to be a serious language, which I hope it does. Then we do need to be able to add negative numbers, keep floats and double, ints, etc. Also pass should be "transaction". Goes well with the whole Trump theme.
And unless there is going to be a automatic way of typing key words, for example: instead of typing a long word like generate it could be shortened. Or make it show a list of key words like Java does. Then we can either just hit enter or tab and it auto-enters it for us. Kind of like how the Linux terminal commands go. This would be very helpful and less time consuming.

**Comment by samshadwell** [comment]
I don't know what you mean by "serious" language. We've already developed it to the point where it is Turing complete (ish, I think, sans the infinite memory part). Also, you're asking specifically for an autocomplete feature, which isn't a language feature, that's more of a feature of a particular IDE or text editor (or the bash shell) to include autocomplete for different languages. It's a stretch goal of ours to develop some kind of plugin for a text editor like Sublime, but that's long after we get the rest of the language working as intended.

**Comment by andy1945** [comment]
Hahhah..no auto complete... I have died......  U should add lol
