### ISSUE TITLE
TrumpScript should handle Race Conditions in multi-threaded applications by:

### ISSUE THREAD

**Issue by TillaTheHun0** [samshadwell/TrumpScript#90]
Terminating threads with the least amount of resources, along with all their children, reallocating the resources to the most privileged thread. In fact, TrumpScript should only run on a single, American thread. One Thread, Under Trump, Indivisible, With Comb-Overs and 2 Corinthians for all.

**Comment by vipulkohli** [comment]
The main race conditions right now are Iowa, New Hampshire, and South Carolina as the first states to primary and caucus! These will be resolved in a few weeks.

**Comment by Googulator** [comment]
You're not trying to play the race card, are you?

**Comment by samshadwell** [comment]
See a76f078
