### ISSUE TITLE
the Joke is So stupid

### ISSUE THREAD

**Issue by yank1** [samshadwell/TrumpScript#95]
I'm from China. When I was young, I think China is a autocracy, and want to change it. But when I've been to USA, I see patriotism everywhere like 60th in China. Suddenly I know, people in China has more freedom than US now.

Freedom is the mother of creativity. Patriotism is the way to lose it.

**Comment by vipulkohli** [comment]
agreed. America is a one party state. Each of the 50 states have already pledged allegiance to a political party, so you can accurately decide an election a month into the campaign trail.
