### ISSUE TITLE
They Say He Doesn't Like China... He Loves China

### ISSUE THREAD

**Issue by airbreather** [samshadwell/TrumpScript#97]
I was looking at [this bit of code](https://github.com/samshadwell/TrumpScript/blob/246e6e0954e9320314b9e69cfac5590cbadb8ebe/src/trumpscript/utils.py#L72-L73), as well as [this](https://github.com/samshadwell/TrumpScript/blob/246e6e0954e9320314b9e69cfac5590cbadb8ebe/src/trumpscript/utils.py#L90-L91), which suggests that Trump doesn't like China.

[But he loves China](https://youtu.be/RDrfE9I8_hs?t=1m33s).

This is related to #74.

**Comment by yuxuanchen1997** [comment]
"How could I dislike China?" --Donald Trump

**Comment by YixuanFranco** [comment]
example should be:

Let's say China,
China, China, China, China, China…
I know China very well,
China, China, China, China, China...

**Comment by samshadwell** [comment]
See a76f078
