### ISSUE TITLE
TrumpScript examples

### ISSUE THREAD

**Issue by keyvank** [samshadwell/TrumpScript#98]
Please add some sample TS codes in the repository!

**Comment by Nateowami** [comment]
It's already in [test/test_files](https://github.com/samshadwell/TrumpScript/tree/master/test/test_files).

**Comment by seyfer** [comment]
Name of folder is not self-explanatory and should be renamed to Examples, because now people think about unit tests, not about test examples

**Comment by pllim** [comment]
Examples are for socialists!

**Comment by samshadwell** [comment]
Done.
